### ISSUE TITLE
default recording folder

### ISSUE THREAD

**Issue by oxyhexagen** [A3DV/VIRec#2]
Thanks for your great work,my device got some compatibility issues with the menu item(IMU,Setting),could you please tell me where is the default setting of result location,to avoid modifying.

**Comment by mojabyte** [comment]
All data sessions are saved in `/Android/data/io.a3dv.VIRec/files/data/` on the SD card. Each data session is stored in a folder named after the local time at the start of recording.

**Comment by oxyhexagen** [comment]
I found them,thanks a million!
